name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main  # Déclenche le pipeline uniquement sur des pushs sur la branche principale (main)

jobs:
  build-and-push:
    runs-on: windows-latest  # Utilisation de l'agent GitHub Actions sous Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Clone le code source du dépôt

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1  # Configure Docker Buildx pour la construction

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Utilisation d'un secret pour sécuriser le nom d'utilisateur DockerHub
        password: ${{ secrets.DOCKER_PASSWORD }}  # Utilisation d'un secret pour sécuriser le mot de passe DockerHub

    - name: Build and tag Docker image
      run: |
        docker build -t ngalla591/basic-http-server:${{ github.sha }} .  # Utilise le SHA du commit pour le tag unique
        docker tag ngalla591/basic-http-server:${{ github.sha }} ngalla591/basic-http-server:latest  # Taguer avec "latest"
      
    - name: Push Docker image
      run: |
        docker push ngalla591/basic-http-server:${{ github.sha }} 
