name: Docker CI/CD Pipeline essai

on:
  push:
    branches:
      - main  # Déclenche le pipeline uniquement sur des pushs sur la branche principale (main)

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Utilisation d’un environnement Linux (plus stable pour Docker)

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Clone le code source du dépôt

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Active Buildx pour une meilleure compatibilité

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Authentification sécurisée via secrets
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and tag Docker image
      run: |
        docker build --cache-from=type=registry,ref=ngalla591/basic-http-server:latest \
                     --cache-to=type=inline \
                     -t ngalla591/basic-http-server:${{ github.sha }} .
        docker tag ngalla591/basic-http-server:${{ github.sha }} ngalla591/basic-http-server:latest  # Ajout du tag "latest"
      
    - name: Push Docker image
      run: |
        docker push ngalla591/basic-http-server:${{ github.sha }}  # Push du tag SHA unique
        docker push ngalla591/basic-http-server:latest  # Push du tag "latest"
